param(
    [string]$Device = "cuda",
    [double[]]$GapPercents = @(0.4, 0.6, 1.0),
    [switch]$Quick,
    [switch]$Regenerate,
    [switch]$Retrain,
    [switch]$SkipPhysicsMetrics
)

$ErrorActionPreference = "Stop"

$Python = ".\venv\Scripts\python.exe"
if (-not (Test-Path $Python)) {
    $Python = "python"
}

if ($Quick) {
    $Epochs = 3
    $TargetTrain = 1200
    $TargetVal = 400
    $TargetTestSeen = 500
    $TargetTestInterp = 400
}
else {
    $Epochs = 80
    $TargetTrain = 20000
    $TargetVal = 2500
    $TargetTestSeen = 4400
    $TargetTestInterp = 2200
}

Write-Host ""
Write-Host ("=" * 104)
Write-Host "Exp22 COMPLETE: physical g-gap sweep for a1 + gamma"
Write-Host ""
Write-Host "Important: this does NOT edit g values by hand."
Write-Host "Every g is generated by the unchanged physical forward model."
Write-Host "The experiment starts from the requested g-space gap, then automatically chooses"
Write-Host "the densest regular (a1,gamma) grid whose generated g curves satisfy that gap."
Write-Host ""
Write-Host "Network / loss   : SAME pairwise MLP as Exp20/Exp21/Exp22A"
Write-Host "q2 points        : 100"
Write-Host "training noise   : 0.2%"
Write-Host "test noise       : 0% and 0.2% (plus 1% for reference)"
Write-Host "g gap targets    : $($GapPercents -join ', ') % RMS(g)"
Write-Host "quick            : $Quick"
Write-Host ("=" * 104)

foreach ($Gap in $GapPercents) {
    if ($Gap -le 0) {
        throw "All GapPercents must be > 0"
    }

    $GapTag = ("{0:g}" -f $Gap).Replace(".", "p")
    $DataDir = ".\data_exp22a_g_gap_${GapTag}pct"
    $OutputDir = ".\validation_results\exp22a_g_gap_${GapTag}pct"
    $Metadata = Join-Path $DataDir "metadata.json"
    $Summary = Join-Path $OutputDir "exp22a_summary.csv"

    Write-Host ""
    Write-Host ("-" * 104)
    Write-Host "Target physical g RMS gap >= $Gap%"
    Write-Host "data   : $DataDir"
    Write-Host "result : $OutputDir"
    Write-Host ("-" * 104)

    if ($Regenerate -or -not (Test-Path $Metadata)) {
        Write-Host "[data] Selecting parameter grid from the requested g-space separation ..."
        & $Python "data_generate_exp22_rms_gseparated_a1gamma.py" `
            --output-dir $DataDir `
            --target-g-gap-percent $Gap `
            --reference-noise 0.002 `
            --a1-min 0.05 `
            --a1-max 0.20 `
            --gamma-min 0.01 `
            --gamma-max 1.0 `
            --min-a1-count 2 `
            --max-a1-count 11 `
            --min-gamma-count 2 `
            --max-gamma-count 11 `
            --q2-points 100 `
            --noise-levels "0,0.002,0.01" `
            --train-noise-level 0.002 `
            --target-train-samples $TargetTrain `
            --target-val-samples $TargetVal `
            --target-test-seen-samples $TargetTestSeen `
            --target-test-interp-samples $TargetTestInterp `
            --compressed `
            --overwrite

        if ($LASTEXITCODE -ne 0) {
            throw "Exp22 data generation failed for g gap $Gap% with exit code $LASTEXITCODE"
        }
    }
    else {
        Write-Host "[data] Existing data found; generation skipped. Use -Regenerate to rebuild."
    }

    if ($Retrain -or -not (Test-Path $Summary)) {
        Write-Host "[train] Training the unchanged pairwise MLP ..."
        $TrainArgs = @(
            "train_exp20_pairwise.py",
            "--mode", "a1gamma",
            "--data-dir", $DataDir,
            "--output-dir", $OutputDir,
            "--result-prefix", "exp22a",
            "--device", $Device,
            "--epochs", $Epochs,
            "--batch-size", 256,
            "--eval-batch-size", 512,
            "--patience", 15
        )
        if ($Quick -or $SkipPhysicsMetrics) {
            $TrainArgs += "--skip-physics-metrics"
        }
        & $Python @TrainArgs
        if ($LASTEXITCODE -ne 0) {
            throw "Exp22 training failed for g gap $Gap% with exit code $LASTEXITCODE"
        }
    }
    else {
        Write-Host "[train] Existing summary found; training skipped. Use -Retrain to rerun."
    }
}

Write-Host ""
Write-Host "[summary] Aggregating continuous gamma-regression results ..."
$GapText = ($GapPercents | ForEach-Object { "{0:g}" -f $_ }) -join ","
& $Python "analyze_exp22_g_gap_sweep.py" `
    --gap-percents $GapText `
    --data-root "." `
    --result-root ".\validation_results" `
    --output-dir ".\validation_results\exp22_g_gap_sweep" `
    --result-prefix "exp22a"

if ($LASTEXITCODE -ne 0) {
    throw "Exp22 sweep analysis failed with exit code $LASTEXITCODE"
}

Write-Host ""
Write-Host ("=" * 104)
Write-Host "Exp22 g-gap sweep complete."
Write-Host "Read first:"
Write-Host "  .\validation_results\exp22_g_gap_sweep\exp22_g_gap_sweep_teacher_summary.csv"
Write-Host "  .\validation_results\exp22_g_gap_sweep\g_gap_vs_gamma_recovery.png"
Write-Host "  .\validation_results\exp22_g_gap_sweep\g_gap_vs_retained_resolution.png"
Write-Host ("=" * 104)
